name: Deploy Bicep file
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: azure-bicep-3stages-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep to resource group
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: snbiceprg
          template: ./main.bicep
          parameters: ./environments/dev/dev_paramvalues.bicepparam vmAdminPassword=${{ secrets.VM_PASSWORD }}
          deploymentMode: Incremental
          deploymentName: envDeployment
