name: Deploy Bicep file
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: azure-bicep-3stages-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file
        run: |
          az deployment group create \
            --name envDeployment \
            --resource-group snbiceprg \
            --template-file main.bicep \
            --parameters ./environments/dev/dev_paramvalues.bicepparam \
            --parameters vmAdminPassword="${{ secrets.VM_PASSWORD }}" \
            --mode Incremental
